import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import About from "../sections/About";
import Header from "../sections/Header";
import Project from "../sections/Project";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";
import Contact from "../sections/Contact";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>David Faith Odesola</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Header />
        <About />
        <Project />
        <Contact />
        <Footer />
      </main>
    </div>
  );
}
